ignore:
  - "examples/**" # test helpers used to test Pub/Subs

comment: false

coverage:
  precision: 0
  status:
    patch:
      default:           
        target: 70%     
        threshold: 5%
        informational: false
    project:
      default:
        target: 70%      # ← Mude de auto para um valor fixo
        threshold: 5%
        informational: false