name: main
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: ./.github/workflows/common.yml
    with:
      codecov: true
      coverage: false
      threshold: 70
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
