name: master
on:
  push:
    branches:
      - master
jobs:
  ci:
    uses: ./.github/workflows/common.yml
    with:
      codecov: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
